---
slug: network
filename: network
title: مقدمه‌ای بر شبکه‌های کامپیوتری
subtitle: به کوشش جمعی از دانشجویان
description: این کتاب ترجمه خیلی ‌آزادی از کتاب Computer Networking A TopDown Approach است.
author: سینا کاشی‌پزها
copyright: 2017
uuid: c8ffb61a-f5a3-43ea-bab3-ee5893a8480d
